stages:
  - build
  - use

build_image:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

use_image:
  stage: use
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker run -d --name model -p 8001:8000 "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - sleep 10
    - docker run --rm --network host curlimages/curl:latest -s -X POST http://127.0.0.1:8001/predict -H "Content-Type: application/json" -d '{"end_station_name":"W 43 St & 6 Ave","count_30":2.0,"count_60":8.0,"count_120":16.0,"month":3,"weekday":1,"hour":14,"hour_part":0}'
