name: Build model

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

  use_image:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Run model
        run: docker run -d --name model -p 8001:8000 ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Wait for model
        run: sleep 10

            - name: Run inference
        run: |
          curl -s -X POST http://127.0.0.1:8001/predict \
            -H "Content-Type: application/json" \
            -d '{"end_station_name":"W 43 St & 6 Ave","count_30":2.0,"count_60":8.0,"count_120":16.0,"month":3,"weekday":1,"hour":14,"hour_part":0}'
